# Generated by Django 5.0 on 2024-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Conteúdo', 'verbose_name_plural': 'Conteúdo'},
        ),
        migrations.AddField(
            model_name='content',
            name='download_link',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link para o cliente fazer o download de todas as midias.'),
        ),
        migrations.AddField(
            model_name='content',
            name='matterport_embed',
            field=models.TextField(default='old', max_length=1000, verbose_name='Codigo da Matterport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='content',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='content',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_link1',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link para o video no youtube.'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_link2',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link para o video no youtube.'),
        ),
        migrations.AddField(
            model_name='content',
            name='video_link3',
            field=models.CharField(blank=True, max_length=300, verbose_name='Link para o video no youtube.'),
        ),
        migrations.AlterModelTable(
            name='content',
            table='content',
        ),
    ]
