# Generated by Django 5.0 on 2024-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_options_content_download_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='address',
            field=models.CharField(default='old', max_length=50, verbose_name='Endereço da Propriedade'),
            preserve_default=False,
        ),
    ]
