# Generated by Django 5.0 on 2024-01-30 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('content', models.ManyToManyField(to='content.content', verbose_name='Content allowed to User')),
            ],
            options={
                'verbose_name': 'End User',
                'verbose_name_plural': 'End Users',
                'db_table': 'end_user',
            },
        ),
    ]
