# Generated by Django 5.0 on 2024-01-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enduser',
            options={'verbose_name': 'CLIENTE', 'verbose_name_plural': 'CLIENTES'},
        ),
    ]
