# Generated by Django 5.0 on 2024-01-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuário'},
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='email',
            field=models.EmailField(max_length=194, unique=True, verbose_name='Email do Usuário'),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuário está ATIVO'),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Usuário é um empregado nosso'),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Usuário é um administrador'),
        ),
    ]
